title = "CircleCityCon 5.0"
baseURL = "http://circlecitycon.com"
languageCode = "en-us"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 5 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  description = ""
  facebook = ""
  twitter = "https://twitter.com/CircleCityCon"
  instagram = ""
  youtube = ""
  background_color_class = "bg-black"
  featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  mainSections = ["news"]

[menu]
  [[menu.main]]
  identifier  = "bios"
  parent      = "Schedule"
  name        = "Bios"
  url         = "/bios/"

  [[menu.main]]
  identifier  = "talks"
  parent      = "Schedule"
  name        = "Talks"
  url         = "/talks/"

  [[menu.main]]
  identifier  = "training"
  parent      = "Schedule"
  name        = "Training"
  url         = "/training/"